spring:
  application:
    name: payment-service

  datasource:
    url: jdbc:postgresql://localhost:5434/paymentdb
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

razorpay:
  api:
    key: ""
    secret: ""

stripe:
  api:
    key: ""

server:
  port: 5006