spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://localhost:5434/userdb
    username: postgres
    password : postgres
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 5001
