spring:
  application:
    name: category-service

  datasource:
    url: jdbc:postgresql://localhost:5434/categorydb
    username: postgres
    password : postgres
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 5003
