spring:
  application:
    name: service-offering
  datasource:
    url: jdbc:postgresql://localhost:5434/servicesdb
    username: postgres
    password: postgres
  jpa:
      hibernate:
        ddl-auto: update
      database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 5004
